### ISSUE TITLE
is "cache" then third url parameter not work

### ISSUE THREAD

**Issue by BirolKahraman** [Vheissu/Ci-Smarty#43]
Url parameter request "http://localhost/ci/tr/sayfa/adayin-sozu"  then response "http://localhost/ci/tr/sayfa/" this problem helpme please

**Comment by mytharcher** [comment]
Almost same in #34, never resolved.

**Comment by Vheissu** [comment]
Is this issue in regards to dynamic data not updating because the original data is being cached and displayed instead? The nocache helper tag might be the right course of action to bypass this: http://www.smarty.net/docs/en/language.function.nocache.tpl - happy to hear of suggestions to fix this on a code level though.

**Comment by Vheissu** [comment]
Please see above comment and linked issue from above.
